// Product-family rules reviewed against the observed GA4 titles and ad SKUs.
// Rules are inferred mappings, not conversion attribution. Ambiguous targets stay unmatched.
const rules=[];
const add=(name,sku,title,target)=>rules.push({name,sku,title,target});
add('King Tour Pack 颜色 / 五金变体',/^(KTP(?:CR|BL)|RTPBL)(?:-|$)/i,/^(?!.*two tone).*king.*(?:rear )?tour.*(?:trunk )?pack/i,/^Advanblack King Rear Tour Trunk Pack For/i);
add('King Tour Pack 双色款',/^(KTP(?:CR|BL)|RTPBL)(?:-|$)/i,/(?=.*two tone).*king.*(?:rear )?tour.*(?:trunk )?pack/i,/^Advanblack Custom Two Tone King Rear Tour Trunk Pack For/i);
add('Chopped Tour Pack 颜色 / 五金变体',/^CTP(?:CR|BL)(?:-|$)/i,/chopped.*(?:rear )?tour.*(?:trunk )?pack/i,/^Advanblack Chopped Rear Tour Trunk Pack For/i);
add('Razor Tour Pack 颜色 / 五金变体',/^RTP(?:CR|BL)(?:-|$)/i,/razor.*(?:rear )?tour.*(?:trunk )?pack/i,/^Advanblack Razor Rear Tour Trunk Pack For/i);
add('ProTek Touring 后护杠（镀铬）',/^121SBCBT(?:-|$)/i,/chrome.*(?:rear|saddlebag)/i,/^Chrome ProTek Rear Performance Crash Bar Saddlebags Guards/i);
add('ProTek Touring 后护杠',/^121SBCBT(?:-|$)/i,/^(?!.*chrome).*(?:rear.*(?:crash|saddlebag)|saddlebag.*guard)/i,/^ProTek Rear Performance Crash Bar Saddlebags Guards/i);
add('ProTek Two Step 前护杠（镀铬）',/^HPCBT(?:-|$)/i,/chrome.*two step/i,/^Chrome ProTek Front Performance High Way Peg Two Step/i);
add('ProTek Two Step 前护杠',/^HPCBT(?:-|$)/i,/^(?!.*chrome).*two step/i,/^ProTek Front Performance High Way Peg Two Step/i);
add('ProTek One Step 前护杠',/^OSTEG(?:-|$)/i,/^(?!.*chrome).*one step/i,/^ProTek Front Performance High Way Peg One Step/i);
add('ProTek Softail 前护杠（镀铬）',/^LRSTC(?:-|$)/i,/chrome.*crash bar/i,/^Chrome ProTek Front Performance Crash Bar for/i);
add('ProTek Softail 前护杠',/^LRSTC(?:-|$)/i,/^(?!.*chrome).*crash bar/i,/^ProTek Front Performance Crash Bar for\s+'18/i);
add('ProTek Softail 后护杠',/^STRSG(?:-|$)/i,/rear.*(?:crash|saddlebag)/i,/^ProTek Performance Rear Crash Bar with Sliders for Harley M8 Softail/i);
add('ST Style 前整流罩',/^STF(?:-|\s|$)/i,/(?:ST Style|ST Fairing|softail.*front fairing)/i,/^Advanblack Color-Matched ST Style Front fairings/i);
add('T-Sport 前整流罩',/^TSOF(?:-|$)/i,/t-sport fairing/i,/^Advanblack Color Matched T-Sport Fairing/i);
add('中车架导流板',/^MFAD(?:-|$)/i,/mid.frame air deflector/i,/^Mid-Frame Air Deflectors heat shield/i);
add('手护板',/^HG(?:-|$)/i,/hand guard/i,/^Color Matched hand guard for Harley Touring & Softails/i);
add('Softail 下腿整流罩',/^STLF(?:-|$)/i,/lower leg fairing/i,/^COLOR-MATCHED Lower Leg Fairing/i);
add('旧款油箱仪表盖',/^TDC(?:-|$)/i,/tank dash console/i,/^Low-profile Tank Dash Console for '08/i);
add('新款油箱仪表盖',/^121TDC(?:-|$)/i,/tank dash console/i,/^Advanblack Color Matched Tank Dash Console for '23.5/i);
add('AXION 油箱盖',/^121GC(?:-|$)/i,/gas cap/i,/^Axion Billet Aluminum Gas Cap with Carbon Fiber Plate/i);
add('Legacy 新款座椅',/^HSTS121(?:-|$)/i,/legacy.*seat/i,/^Advanblack Legacy Grand Touring Seat for '23.5Up/i);
add('Legacy 旧款座椅',/^HSTS(?:-|$)/i,/legacy.*seat/i,/^Advanblack Legacy Grand Touring Seat for 2009/i);
add('SIK Baggers 旧款座椅',/^SHTS(?:-|$)/i,/sik baggers/i,/^Advanblack "SIK Baggers" Custom Stitching Seat/i);
add('SIK Baggers 新款座椅',/^SIKBS24(?:-|$)/i,/sik baggers/i,/^Advanblack x SIK Baggers Seat for/i);
add('ProMonkey 旧款座椅',/^PROMS(?:-|$)/i,/promonkey/i,/^Advanblack "ProMonkey" Extended Reach Seat/i);
add('ProMonkey 新款座椅',/^24PROMS(?:-|$)/i,/(?:promonkey|professional monkey)/i,/^Advanblack x Professional Monkey Extended Reach Seat/i);
add('Touring 降低套件',/^TLK(?:-|$)/i,/lowering.*block/i,/^2 Inch Lowering blocks Kit/i);
add('2023.5+ 边箱灯',/^121SBLLNB(?:-|$)/i,/saddlebag.*light/i,/^Hyper LED Light w\/ Sequential Red Turn Signal Saddlebags lights For '23.5Up/i);
add('2014–2023 边箱灯',/^SBLL14(?:-|$)/i,/saddlebag.*light/i,/^Hyper LED Light with Sequential Red Turn Signal saddlebags lights For '14/i);
add('旧款整流罩扰流套件',/^RGSK15(?:-|$)/i,/fairing spoiler/i,/^Color Matched Fairing Spoiler Kit for 2017/i);
add('新款整流罩扰流套件',/^RGSK24(?:-|$)/i,/fairing spoiler kit/i,/^Fairing\s+Spoiler Kit with Support Bracket/i);
add('新款侧面扰流罩',/^RGTSK24(?:-|$)/i,/side spoiler/i,/^Side Spoiler Panel Fairings with Support Bracket/i);
add('新款升级下扰流罩',/^RGBSK24(?:-|$)/i,/chin spoiler/i,/^Upgraded Chin Spoiler for '23.5-'26/i);
add('Touring 新款下整流罩',/^121LF(?:-|$)/i,/lower fairing.*23\.5/i,/^Color Matched Lower Fairings for Harley '23.5/i);
add('Touring 旧款下整流罩',/^LF14(?:-|$)/i,/lower vented fairing/i,/^Rushmore Lower Vented Fairings for/i);
add('Vengeance 前脚踏板',/^MFB(?:-|$)/i,/vengeance.*front.*floorboard/i,/^Advanblack Vengeance Front Rider Floorboards/i);
add('Vengeance 后脚踏板',/^PFB(?:-|$)/i,/vengeance.*rear.*floorboard/i,/^Advanblack Vengeance Rear Passenger Floorboards/i);
add('Vengeance 换挡杆',/^SP(?:-|$)/i,/vengeance.*shift/i,/^Advanblack Vengeance Heel Toe Shift Peg Levers/i);
add('碳纤维滑块',/^CNCCFS(?:-|$)/i,/crash bar slider/i,/^Advanblack ProTek Machined CNC Alumium with Carbon Fiber Inlay Crash Bar Slider/i);
add('铝合金滑块',/^CNCS(?:-|$)/i,/crash bar slider/i,/^Advanblack ProTek Machined CNC Alumium Crash Bar Slider/i);
add('AXION 座椅螺栓',/^CNCRSB(?:-|$)/i,/seat bolt/i,/^Axion CNC Machined Knurled Seat Bolt Kit/i);
add('FireBlade 碳纤维后视镜',/^CFFBM(?:-|$)/i,/fireblade.*mirror/i,/^FireBlade Carbon Fiber Performance Mirrors/i);
add('AXION 后视镜',/^CNCCFMRNB(?:-|$)/i,/axion.*mirror/i,/^Axion Performance Style Mirrors/i);
add('Clutch Saver',/^EPC(?:-|$)/i,/clutch/i,/^Advanblack Clutch Saver for/i);
add('碳纤维电池盖',/^(?:FGCFBC|CFBC)(?:-|$)/i,/battery cover/i,/^Carbon Fiber Battery Cover/i);
add('Low Rider 碳纤维前挡泥板',/^(?:FGCFLRSFF|CFLRSFF)(?:-|$)/i,/front fender.*low rider/i,/^Carbon Fiber Front Fender for\s+'20/i);
add('Low Rider 碳纤维后挡泥板',/^CFLRSRF(?:-|$)/i,/rear fender.*low rider/i,/^Carbon Fiber Rear Fender for Harley '20/i);
add('Touring 新款碳纤维前挡泥板',/^121FGCFFF(?:-|$)/i,/front fender.*23\.5/i,/^Carbon Fiber Front Fender for '23.5Up/i);
add('19 寸碳纤维短挡泥板',/^FGCF19FF(?:-|$)/i,/19.*chopped front fender/i,/^Carbon Fiber 19inch Chopped Front Fender/i);
add('Low Rider 碳纤维仪表盖',/^(?:FGCFLRSTDC|CFLRSTDC)(?:-|$)/i,/tank dash console.*low rider/i,/^Carbon Fiber TANK DASH CONSOLE FOR '22/i);
add('ST 碳纤维外整流罩',/^FGCFSTOF(?:-|$)/i,/carbon fiber st outer/i,/^Carbon Fiber ST Outer Fairing/i);
add('碳纤维中车架导流板',/^FGFBMFAD(?:-|$)/i,/mid.frame air deflector/i,/^Carbon Fiber MID-FRAME AIR DEFLECTORS/i);
add('AXION 碳纤维换挡连杆',/^LCFSLS(?:-|$)/i,/shift linkage/i,/^Axion Carbon Fiber Adjustable Shift Linkage/i);
add('AXION 握把',/^HYHGNA(?:-|$)/i,/axion.*grips/i,/^Advanblack AXION Performance Grips for Harley Touring, Softail/i);
add('手护板顺序转向灯',/^HGLL$/i,/hand guard/i,/^Sequential LED Turn Signals & Running Lights for Advanblack Hand Guards/i);
add('旧款可调整流罩导流板',/^BAAD14(?:-|$)/i,/adjustable fairing air deflector/i,/^Advanblack Adjustable Fairing Air Deflectors/i);
add('2013 以前加长边箱',/^SB13(?:-|$)/i,/stretched saddlebag bottom/i,/^Stretched Saddlebags Bottoms for '93/i);
add('2014 加长边箱底',/^SB14(?:-[^\s]+)?$/i,/stretched saddlebag bottom/i,/^4.5'' Stretched Saddlebag Bottoms/i);
add('标准边箱盖',/^SNL14(?:-[^\s]+)?$/i,/standard normal saddlebag lids/i,/^Standard Normal Saddlebag Lids/i);
add('8 寸喇叭边箱盖',/^SL8C14(?:-|$)/i,/saddlebag speaker lids/i,/^8'' Saddlebag Speaker Lids Cover/i);
add('6×9 喇叭边箱盖',/^SL6914(?:-|$)/i,/6x9 saddlebag speaker lids/i,/^Color Matched 6X9 Saddlebag Speaker Lids/i);
add('Dominator 后挡泥板',/^DF(?:-[^\s]+)?$/i,/dominator stretched rear fender/i,/^Dominator Stretched Rear Fender For 2014/i);
add('加长后挡泥板延伸件',/^RFE(?:-|$)/i,/stretched rear fender extension/i,/^Stretched Rear Fender Extension/i);
add('旧款蝙蝠外整流罩',/^DDOF14(?:-|$)/i,/outer fairing batwing/i,/^Outer Fairing Batwing Cowl/i);
add('Bagger Boss 套件',/^BGSB(?:-|\s|$)/i,/bagger boss.*(?:bagger )?kit/i,/^Advanblack Color Matched Bagger Boss Down and Out Bagger Kit/i);
add('Softail Holeshot 边箱套件',/^PBSB(?:-|\s|$)/i,/holeshot.*saddlebag kit.*(?:m8|low rider)/i,/^Color Matched Holeshot 1.0 Performance Saddlebag Kit For M8/i);
add('Holeshot 旧款完整套件',/^PBSB(?:-|\s|$)/i,/holeshot.*chopped bagger kit.*14.*23/i,/^Color Matched Holeshot 1.0 Chopped Bagger Kit for '14/i);
add('Holeshot 新款边箱底',/^121HSSB(?:-|$)/i,/chopped saddlebag.*bottom/i,/^Color Matched Holeshot 2.0 Chopped Saddlebags Bottoms/i);
add('Holeshot 19 寸短前挡泥板',/^19CFF(?:-|$)/i,/holeshot.*19.*front fender/i,/^Color Matched Holeshot Performance 19inch short front fender/i);
add('新款 19 寸包覆前挡泥板',/^19FF24(?:-|$)/i,/19.*(?:wrapper|hugger).*front fender/i,/^19" Reveal Wrapper Hugger Front Fender For '23.5Up/i);
add('旧款 19 寸包覆前挡泥板',/^19FF(?:-|$)/i,/19.*(?:wrapper|hugger).*front fender/i,/^19" Reveal Wrapper Hugger Front Fender For '09/i);
add('旧款 21 寸包覆前挡泥板',/^21FF(?:-|$)/i,/21.*front fender/i,/^21" Reveal Wrapper Hugger Front Fender For '09/i);
export function familyMatch(row,titles){
 if(/\b(?:liner|lining|pad|rack|speaker|luggage)\b/i.test(row.title)&&/tour.*pack/i.test(row.title))return null;
 const matches=[];
 for(const rule of rules){if(!rule.sku.test(row.id)||!rule.title.test(row.title))continue;const target=titles.filter(t=>rule.target.test(t.trim()));if(target.length===1)matches.push({title:target[0],rule:rule.name});}
 const unique=[...new Set(matches.map(x=>x.title))];return unique.length===1?matches[0]:null;
}
export function ruleDiagnostics(titles){return rules.map(r=>({name:r.name,targets:titles.filter(t=>r.target.test(t.trim()))})).filter(x=>x.targets.length!==1);}
