import fs from 'node:fs';
let html=fs.readFileSync('dist/index.html','utf8');
html=html.replace('<th><button data-sort="pmax">PMax CNY ↕</button></th><th><button data-sort="shopping">Shopping CNY ↕</button></th>','<th><button data-sort="google">Google USD ↕</button></th>');
html=html.replace('广告费用仅计入已明确匹配的商品','广告消耗按商品型号汇总颜色 / 五金变体 · 点击商品查看明细');
html=html.replace('商品明细未匹配与非 Catalog / 未拆分消耗分开保留。','有 Product ID 的 Meta 消耗统一归并；没有产品拆分的余额单独保留。');
html=html.replace('按原账户币种核对。不同币种不相加；未分配费用保留。','统一显示 USD；Google 原始 CNY 消耗按 1 USD = 6.8 CNY 换算。未分配费用保留。');
html=html.replace('</main>','<dialog id="detailDialog"><div class="table-tools"><h2 id="detailTitle"></h2><button id="closeDetail">关闭</button></div><p id="detailNote" class="muted"></p><div class="table-wrap"><table><thead><tr><th>广告商品 Title / Product ID</th><th>平台</th><th>匹配依据</th><th>消耗 USD</th></tr></thead><tbody id="detailRows"></tbody></table></div></dialog></main>');
fs.writeFileSync('dist/index.html',html);
let js=fs.readFileSync('dist/app.js','utf8');
js=js.replace("import {aggregate,csvCell,dateValid}","import {aggregate,csvCell,dateValid,keyOf,normalize}");
js=js.replaceAll('colspan="7"','colspan="6"');
js=js.replace('美元与人民币分别显示。','统一以 USD 展示；Google 按固定汇率 6.8 换算。');
js=js.replace("['Google 总消耗 · CNY','¥ '+money(s.google)","['Google 总消耗 · USD','$ '+money(s.google)");
js=js.replace('<td>${esc(r.title)}${r.adRows?','<td><button class="product-link" data-product="${esc(r.title)}">${esc(r.title)}</button>${r.adRows?');
js=js.replace('${num(r.adRows)} 条已匹配广告商品记录','${num(r.adRows)} 条广告商品记录${r.familyRows?` · 含型号归并`:``}');
js=js.replace('<td>${money(r.pmax)}</td><td>${money(r.shopping)}</td>','<td>${money(r.google)}</td>');
js=js.replace("$('next').disabled=page===pages;}","$('next').disabled=page===pages;document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>showDetails(b.dataset.product));}");
js=js.replaceAll('非 Catalog / 待核实广告','未拆到产品的广告余额');
js=js.replaceAll("?'Meta Catalog'", "?'Meta Product ID'");
js=js.replace('${money(r.cost)} ${r.platform===\'google\'?\'CNY\':\'USD\'}','${money(r.platform===\'google\'?r.cost/data.fx.cnyPerUsd:r.cost)} USD');
js=js.replace('已验证映射及你确认的映射','按 SKU 和产品类型推断的型号归并及你确认的映射');
js=js.replace('Meta 仅统计创意带 product_set_id 的 Catalog 广告产品拆分；普通广告即使返回产品拆分也暂不分摊。Google 仅统计 PMax / Shopping 的产品消耗，其他系列保留在核对页。','Meta 按 Product ID 汇总所有可拆分到商品的消耗，包含普通广告中的产品明细。没有 Product ID 明细的余额不分摊。Google 主表合并 PMax / Shopping 消耗，并以 CNY ÷ 6.8 换算为 USD，其他系列保留在核对页。');
js=js.replace('平台日界线不同，日期按各自账户口径筛选；不计算跨币种 ROAS。','型号归并依据 SKU 系列和产品类型，属于规则推断，可点击商品查看来源。不同产品型号和配件不会仅凭文字相似自动合并。日期按各自账户时区筛选。');
js=js.replace('Google：CNY · Asia/Shanghai','Google：原始 CNY → USD ÷ 6.8 · Asia/Shanghai');
js=js.replace("'Meta Catalog USD','PMax CNY','Shopping CNY'","'Meta USD','Google USD'");
js=js.replace('r.meta.toFixed(2),r.pmax.toFixed(2),r.shopping.toFixed(2)','r.meta.toFixed(2),r.google.toFixed(2)');
js=js.replace('page++;page-=2;','page--;');
const begin=js.indexOf('function renderAudit()'),end=js.indexOf('function googleOtherRows()');
js=js.slice(0,begin)+`function renderAudit(){const row=(label,value)=>\`<tr><td>\${label}</td><td>\${money(value)} USD</td></tr>\`;$('auditContent').innerHTML=\`<div class="source-grid">\${result.accounts.map(a=>{const f=a.platform==='google'?data.fx.cnyPerUsd:1;return \`<article class="source-card"><h3>\${esc(a.name)}</h3><table><tbody>\${row('账户总消耗',a.total/f)}\${row('已匹配到 GA4 商品',a.matched/f)}\${row('已拆到产品，商品名待匹配',(a.detail-a.matched)/f)}\${row(a.platform==='meta'?'未拆到 Product ID / 报表差额':'PMax / Shopping 未拆到产品 / 报表差额',(a.eligible-a.detail)/f)}\${a.platform==='google'?row('非 PMax / Shopping，暂不分配',(a.total-a.eligible)/f):''}</tbody></table><p>产品拆分覆盖：\${a.eligible?((a.detail/a.eligible)*100).toFixed(1):'0.0'}% · 已拆分消耗的商品匹配率：\${a.detail?((a.matched/a.detail)*100).toFixed(1):'0.0'}%</p>\${a.platform==='google'?\`<p>原始账户总额：\${money(a.total)} CNY<br>用户指定固定汇率：1 USD = 6.8 CNY</p>\`:''}</article>\`}).join('')}</div><details><summary>查看 Google 暂不分配的广告系列</summary><table><thead><tr><th>广告系列</th><th>类型</th><th>消耗 USD</th></tr></thead><tbody>\${googleOtherRows()}</tbody></table></details>\`;}
`+js.slice(end);
js=js.replace('${money(r.cost)}</td></tr>`).join(\'\');}','${money(r.cost/data.fx.cnyPerUsd)}</td></tr>`).join(\'\');}');
js+=`\nfunction showDetails(title){const titles=[...new Set(data.ga4.map(r=>r.title))];const m=new Map();for(const r of data.ads){if(r.date<$('start').value||r.date>$('end').value)continue;const key=keyOf(r);let target=mappings[key]||data.verifiedMappings[key];if(!target){const same=titles.filter(t=>normalize(t)===normalize(r.title));if(same.length===1)target=same[0];}if(target!==title)continue;const id=r.platform+'|'+r.id+'|'+r.title;if(!m.has(id))m.set(id,{...r,cost:0,reason:mappings[key]?'手动确认':data.mappingEvidence[key]?.rule||'规范化同名'});m.get(id).cost+=r.cost/(r.platform==='google'?data.fx.cnyPerUsd:1);}$('detailTitle').textContent=title;$('detailNote').textContent='按选定日期汇总。型号归并为规则推断；下表保留广告原始 Title 和 Product ID，可逐项核对。';$('detailRows').innerHTML=[...m.values()].sort((a,b)=>b.cost-a.cost).map(r=>\`<tr><td>\${esc(r.title)}<div class="small">\${esc(r.id)}</div></td><td>\${r.platform==='google'?'Google':'Meta'}</td><td>\${esc(r.reason)}</td><td>\${money(r.cost)}</td></tr>\`).join('')||'<tr><td colspan="4" class="empty">此商品暂无已匹配的消耗，请查看待匹配产品。</td></tr>';$('detailDialog').showModal();}\n$('closeDetail').onclick=()=>$('detailDialog').close();\n`;
fs.writeFileSync('dist/app.js',js);
fs.appendFileSync('dist/style.css','\n.product-link{padding:0;border:0;background:none;text-align:left;font-size:14px;line-height:1.6;color:#202936}.product-link:hover{color:#b65323;background:none;text-decoration:underline}.mapping-row{display:flex;gap:8px;margin-top:12px}.mapping-input{min-width:200px;flex:1}#pending td:last-child{text-align:left;min-width:320px;max-width:540px;font-size:13px;line-height:1.7}dialog{border:1px solid #dce1e7;border-radius:10px;padding:25px;width:min(1150px,94vw);max-height:85vh;color:#202936}dialog::backdrop{background:#171d2780}dialog h2{flex:1;line-height:1.6;font-size:17px}dialog .table-wrap{max-height:58vh;margin-top:20px}dialog td:nth-child(3){text-align:left}\n');
